### ISSUE TITLE
Feature Request: Allow Custom OpenAi - Compatible API

### ISSUE THREAD

**Issue by LumiWasTaken** [Kiln-AI/Kiln#42]
Hiya,

i've been using Kiln for a bit with a supplied OpenAi Key.
But we all know that Cloud services are expensive and not very customizeable.

Hence why i'd have hoped for more Local support.

Two issues.
- I have an OpenAi Compatible API e.g. vLLM or Aphrodite but I cannot reference it.
Solution: Allow the user to set a custom URL for an Self-hosted OpenAi instance or using a MITM Proxy to control costs and usage.

- Ollama is Running on a different host. Locally I run the Kiln Studio client on my Device but if the Ollama Service is running e.g. on a different IP or Port this will throw a simple error.
Solution: Allow the user to set a custom URL for the Ollama Instance.

In general I think it is important, especially with Synthetic Data, to support locally hosted models.

Thank you!

**Comment by scosman** [comment]
Both good ideas. I'll get to them at some point. I also need to update that UX a bit, like changing a key after it is set.

Short term, you can set `ollama_base_url` in your settings file (~/.kiln_ai/settings.yaml) to target any Ollama instance. Needs UI but it's there.

```
ollama_base_url: http://localhost:11434
```

**Comment by scosman** [comment]
Ollama request complete here: https://github.com/Kiln-AI/Kiln/commit/57f51f337f84cba260a11bb5b1d9cd69d0de03bc

**Comment by scosman** [comment]
Edit title to make this issue specific to OpenAI compatibility. Ollama URL done and will be in next release.

**Comment by sammcj** [comment]
I just saw https://github.com/Kiln-AI/Kiln/issues/42#issuecomment-2492676966, this is great!

However, I tried it out and it still seems to default to the local Ollama instance rather than the remote instance configured in `~/.kiln_ai/settings.yaml` - is there something that needs to be done to update an existing project to use the new Ollama instance? (Kiln Version 0.7.0)

**Comment by scosman** [comment]
@LumiWasTaken this is in the v0.8 beta release. Have a second to try it out? 

https://github.com/Kiln-AI/Kiln/releases/tag/v0.8.0-beta

**Comment by LumiWasTaken** [comment]
I currently can't. I'll let you know.

**Comment by LumiWasTaken** [comment]
Seems to work, no issues spotted :+1: well done
