### ISSUE TITLE
Feature Request: Add support for LiteLLM

### ISSUE THREAD

**Issue by kirankc** [Kiln-AI/Kiln#89]
Would be great to see Kiln support LiteLLM

**Comment by scosman** [comment]
I just shipped a pre-release build which support any OpenAI compatible endpoint, which should work with LiteLLM. Want to try it and let me know if it works for you?

https://github.com/Kiln-AI/Kiln/releases/tag/v0.8.0-beta

**Comment by kirankc** [comment]
That's great news @scosman. When I add the LiteLLM API endpoint in the Kiln UI, it says the endpoint is connected, but the models don't up for selection. If it helps, LiteLLM API can be found at -> https://litellm-api.up.railway.app/

<img width="633" alt="image" src="https://github.com/user-attachments/assets/dc5cf252-41fe-4936-a664-e0aef6f57cca" />

<img width="448" alt="image" src="https://github.com/user-attachments/assets/f82f526b-e287-4714-86f4-ff66e968ee58" />

<img width="537" alt="image" src="https://github.com/user-attachments/assets/6cb49667-9b66-4ccc-aa4b-b8137190fc2b" />

**Comment by scosman** [comment]
Nice bug. Can you show the response to /v1/models?

It should be the same but it also should work with that output. 

Maybe try restating kiln to kill the cache as well. 

Thanks!

**Comment by kirankc** [comment]
Sure @scosman. Here is the screenshot for v1. Tried restarting Kiln but no luck. Is there a way to look at the logs?

<img width="486" alt="image" src="https://github.com/user-attachments/assets/dee36f76-d62f-4673-ace9-0000978414fe" />

**Comment by scosman** [comment]
Hmm, I just tried it and it worked fine with LiteLLM. The only trick was I had to stop Kiln, and restart it while LiteLLM was running. If I start Kiln first it caches the model list at that moment (nothing). Can you try that flow and see if you can get it working?

<img width="314" alt="Screenshot 2024-12-23 at 9 26 10 AM" src="https://github.com/user-attachments/assets/c23c0b12-e5b5-4c58-bea2-79660c9abe5c" />

I'll make it a little smarter on not caching error results in the next release.
